### ISSUE TITLE
[META] Стек технологий и архитектура

### ISSUE THREAD

**Issue by sigorilla** [banditi/chat#1]
@banditi/codebusters 

Давайте обсудим основу. Пока предлагаю заюзать nodejs для сервера и какую-нибудь хипстерскую штуку на клиенте.

----

UPD:

- [ ] common
  - [x] CI - travis #3 
  - [ ] ~~yarn~~ - #4
  - [x] husky + eslint - кодстайл #3 
  - [ ] docker #11 
- [ ] server - nodejs 6
  - [x] express - веб сервер #3
    - [ ] helmet #10
  - [ ] ~~pug - шаблонизатор, или что-то похожее~~
  - [ ] vue SSR
  - [x] mocha + chai + istanbul - тесты #3 
  - [ ] sequelize - провайдер к Postgres #2 
- [ ] client
  - [ ] vue.js #5 
  - [ ] webpack #5
  - [ ] тестирование (unit, func, regression, e2e, ...) ?

**Comment by sigorilla** [comment]
Короче предлагаю такое:

* nodejs 6
  * express - веб сервер
  * pug - шаблонизатор
  * husky + eslint - кодстайл
  * mocha + chai + istanbul - тесты

По поводу клиента открыт к предложениям. Можно пробнуть React

**Comment by sigorilla** [comment]
На клиенте можно ещё посмотреть в сторону ServiceWorker для загрузки статики и какой-нибудь оффлайн херни
